-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.accounting_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  name character varying NOT NULL,
  period_type character varying NOT NULL CHECK (period_type::text = ANY (ARRAY['MONTHLY'::character varying, 'QUARTERLY'::character varying, 'ANNUAL'::character varying]::text[])),
  fiscal_year integer NOT NULL,
  period_number integer NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status character varying NOT NULL DEFAULT 'OPEN'::character varying CHECK (status::text = ANY (ARRAY['OPEN'::character varying, 'SOFT_CLOSE'::character varying, 'HARD_CLOSE'::character varying, 'LOCKED'::character varying]::text[])),
  ap_closed boolean DEFAULT false,
  ap_closed_by uuid,
  ap_closed_at timestamp with time zone,
  ar_closed boolean DEFAULT false,
  ar_closed_by uuid,
  ar_closed_at timestamp with time zone,
  gl_closed boolean DEFAULT false,
  gl_closed_by uuid,
  gl_closed_at timestamp with time zone,
  locked_by uuid,
  locked_at timestamp with time zone,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT accounting_periods_pkey PRIMARY KEY (id),
  CONSTRAINT accounting_periods_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT accounting_periods_ap_closed_by_fkey FOREIGN KEY (ap_closed_by) REFERENCES public.users(id),
  CONSTRAINT accounting_periods_ar_closed_by_fkey FOREIGN KEY (ar_closed_by) REFERENCES public.users(id),
  CONSTRAINT accounting_periods_gl_closed_by_fkey FOREIGN KEY (gl_closed_by) REFERENCES public.users(id),
  CONSTRAINT accounting_periods_locked_by_fkey FOREIGN KEY (locked_by) REFERENCES public.users(id),
  CONSTRAINT accounting_periods_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT accounting_periods_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.alumni_employment_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  student_id uuid NOT NULL,
  employment_status character varying,
  employment_type character varying,
  employer_name text,
  position text,
  date_hired date,
  salary_range character varying,
  is_related_to_course boolean DEFAULT true,
  employer_address text,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT alumni_employment_reports_pkey PRIMARY KEY (id),
  CONSTRAINT alumni_employment_reports_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT alumni_employment_reports_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.assessment_registrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  registration_code text,
  student_id uuid NOT NULL,
  qualification_id uuid NOT NULL,
  sponsor_id uuid,
  billing_party text NOT NULL DEFAULT 'SELF'::text CHECK (billing_party = ANY (ARRAY['SELF'::text, 'SPONSOR'::text])),
  assessment_type text NOT NULL DEFAULT 'FULL_ASSESSMENT'::text CHECK (assessment_type = ANY (ARRAY['FULL_ASSESSMENT'::text, 'REASSESSMENT'::text, 'COC'::text, 'RPL'::text])),
  assessment_date date,
  status text NOT NULL DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'BILLED'::text, 'PAID'::text, 'ASSESSED'::text, 'COMPLETED'::text, 'COMPETENT'::text, 'NOT_YET_COMPETENT'::text, 'CANCELLED'::text])),
  billing_status text NOT NULL DEFAULT 'UNBILLED'::text CHECK (billing_status = ANY (ARRAY['UNBILLED'::text, 'BILLED'::text, 'PARTIALLY_BILLED'::text])),
  total_fees numeric DEFAULT 0,
  billed_amount numeric DEFAULT 0,
  invoice_id uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT assessment_registrations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.atc_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT atc_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.atc_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid NOT NULL,
  atc_code character varying NOT NULL UNIQUE,
  description text NOT NULL,
  taxpayer_type character varying NOT NULL CHECK (taxpayer_type::text = ANY (ARRAY['Individual'::character varying, 'Corporation'::character varying, 'Both'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT atc_items_pkey PRIMARY KEY (id),
  CONSTRAINT atc_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.atc_categories(id)
);
CREATE TABLE public.atc_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  atc_item_id uuid NOT NULL,
  rate numeric DEFAULT NULL::numeric,
  rate_label character varying DEFAULT NULL::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT atc_rates_pkey PRIMARY KEY (id),
  CONSTRAINT atc_rates_atc_item_id_fkey FOREIGN KEY (atc_item_id) REFERENCES public.atc_items(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  user_id uuid,
  action character varying NOT NULL,
  entity_type character varying,
  entity_id uuid,
  details text,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.bank_accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  bank_name character varying NOT NULL,
  account_number character varying NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['CHECKING'::character varying, 'SAVINGS'::character varying, 'CREDIT'::character varying]::text[])),
  gl_account_id uuid,
  currency character varying DEFAULT 'PHP'::character varying,
  balance numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT bank_accounts_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT bank_accounts_gl_account_id_fkey FOREIGN KEY (gl_account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT fk_bank_gl_account FOREIGN KEY (gl_account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT bank_accounts_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.bank_deposit_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  deposit_id uuid NOT NULL,
  payment_id uuid,
  description character varying NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  check_number character varying,
  check_date date,
  payer_name character varying,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT bank_deposit_lines_pkey PRIMARY KEY (id),
  CONSTRAINT bank_deposit_lines_deposit_id_fkey FOREIGN KEY (deposit_id) REFERENCES public.bank_deposits(id),
  CONSTRAINT bank_deposit_lines_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT bank_deposit_lines_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.bank_deposits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  deposit_no character varying NOT NULL,
  bank_account_id uuid NOT NULL,
  reference_no character varying,
  deposit_date date NOT NULL DEFAULT CURRENT_DATE,
  status character varying NOT NULL DEFAULT 'DRAFT'::character varying CHECK (status::text = ANY (ARRAY['DRAFT'::character varying, 'POSTED'::character varying, 'VOIDED'::character varying]::text[])),
  total_amount numeric NOT NULL DEFAULT 0,
  cash_amount numeric NOT NULL DEFAULT 0,
  check_amount numeric NOT NULL DEFAULT 0,
  journal_entry_id uuid,
  posted_at timestamp with time zone,
  posted_by uuid,
  voided_at timestamp with time zone,
  voided_by uuid,
  void_reason text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT bank_deposits_pkey PRIMARY KEY (id),
  CONSTRAINT bank_deposits_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT bank_deposits_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
  CONSTRAINT bank_deposits_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
  CONSTRAINT bank_deposits_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES public.users(id),
  CONSTRAINT bank_deposits_voided_by_fkey FOREIGN KEY (voided_by) REFERENCES public.users(id),
  CONSTRAINT bank_deposits_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT bank_deposits_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT bank_deposits_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.bank_reconciliations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  bank_account_id uuid NOT NULL,
  as_of_date date NOT NULL,
  statement_balance numeric NOT NULL DEFAULT 0,
  book_balance numeric NOT NULL DEFAULT 0,
  cleared_balance numeric NOT NULL DEFAULT 0,
  difference numeric NOT NULL DEFAULT 0,
  status character varying DEFAULT 'IN_PROGRESS'::character varying,
  reconciliation_details text,
  reconcilied_by uuid,
  reconcilied_at timestamp without time zone,
  locked_by uuid,
  locked_at timestamp without time zone,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp without time zone,
  deleted_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT bank_reconciliations_pkey PRIMARY KEY (id),
  CONSTRAINT bank_reconciliations_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT bank_reconciliations_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
  CONSTRAINT bank_reconciliations_reconcilied_by_fkey FOREIGN KEY (reconcilied_by) REFERENCES public.users(id),
  CONSTRAINT bank_reconciliations_locked_by_fkey FOREIGN KEY (locked_by) REFERENCES public.users(id)
);
CREATE TABLE public.batches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  qualification_id uuid NOT NULL,
  trainer_id uuid NOT NULL,
  sponsor_id uuid,
  location_id uuid,
  batch_code character varying NOT NULL,
  name character varying NOT NULL,
  year integer NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status character varying DEFAULT 'PLANNED'::character varying CHECK (status::text = ANY (ARRAY['PLANNED'::character varying, 'ONGOING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying]::text[])),
  max_students integer NOT NULL,
  current_students integer DEFAULT 0,
  student_ids ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  billable_student_limit integer,
  CONSTRAINT batches_pkey PRIMARY KEY (id),
  CONSTRAINT batches_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT batches_qualification_id_fkey FOREIGN KEY (qualification_id) REFERENCES public.qualifications(id),
  CONSTRAINT batches_trainer_id_fkey FOREIGN KEY (trainer_id) REFERENCES public.trainers(id),
  CONSTRAINT batches_sponsor_id_fkey FOREIGN KEY (sponsor_id) REFERENCES public.sponsors(id),
  CONSTRAINT batches_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.bills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  reference text NOT NULL,
  bill_date date NOT NULL,
  due_date date,
  currency text DEFAULT 'PHP'::text,
  lines jsonb NOT NULL DEFAULT '[]'::jsonb,
  vat_purchases numeric DEFAULT 0,
  input_vat numeric DEFAULT 0,
  non_vat_purchases numeric DEFAULT 0,
  total_ewt numeric DEFAULT 0,
  gross_amount numeric NOT NULL,
  net_payable numeric NOT NULL,
  status text DEFAULT 'DRAFT'::text CHECK (status = ANY (ARRAY['DRAFT'::text, 'POSTED'::text, 'PAID'::text, 'PARTIALLY_PAID'::text, 'CANCELLED'::text])),
  journal_entry_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT bills_pkey PRIMARY KEY (id),
  CONSTRAINT bills_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT bills_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT bills_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id)
);
CREATE TABLE public.chart_of_accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  class character varying NOT NULL CHECK (class::text = ANY (ARRAY['ASSET'::character varying, 'LIABILITY'::character varying, 'EQUITY'::character varying, 'REVENUE'::character varying, 'EXPENSE'::character varying]::text[])),
  parent_id uuid,
  is_header boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chart_of_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT chart_of_accounts_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT chart_of_accounts_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.check_number_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  bank_account_id uuid NOT NULL UNIQUE,
  prefix character varying DEFAULT ''::character varying,
  start_number integer DEFAULT 1,
  current_number integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT check_number_settings_pkey PRIMARY KEY (id),
  CONSTRAINT check_number_settings_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT check_number_settings_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id)
);
CREATE TABLE public.check_vouchers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  check_number character varying NOT NULL,
  bank_account_id uuid NOT NULL,
  payee_id uuid,
  payee_type character varying CHECK (payee_type::text = ANY (ARRAY['VENDOR'::character varying, 'EMPLOYEE'::character varying, 'OTHER'::character varying]::text[])),
  payee_name character varying NOT NULL,
  check_date date NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  amount_in_words character varying,
  status character varying NOT NULL DEFAULT 'DRAFT'::character varying CHECK (status::text = ANY (ARRAY['DRAFT'::character varying, 'PRINTED'::character varying, 'RELEASED'::character varying, 'CLEARED'::character varying, 'VOIDED'::character varying, 'STALE'::character varying]::text[])),
  payable_ids ARRAY DEFAULT '{}'::uuid[],
  journal_entry_id uuid,
  prepared_by uuid,
  prepared_at timestamp with time zone,
  approved_by uuid,
  approved_at timestamp with time zone,
  printed_by uuid,
  printed_at timestamp with time zone,
  released_by uuid,
  released_at timestamp with time zone,
  cleared_by uuid,
  cleared_at timestamp with time zone,
  voided_by uuid,
  voided_at timestamp with time zone,
  void_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT check_vouchers_pkey PRIMARY KEY (id),
  CONSTRAINT check_vouchers_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT check_vouchers_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
  CONSTRAINT check_vouchers_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
  CONSTRAINT check_vouchers_prepared_by_fkey FOREIGN KEY (prepared_by) REFERENCES public.users(id),
  CONSTRAINT check_vouchers_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT check_vouchers_printed_by_fkey FOREIGN KEY (printed_by) REFERENCES public.users(id),
  CONSTRAINT check_vouchers_released_by_fkey FOREIGN KEY (released_by) REFERENCES public.users(id),
  CONSTRAINT check_vouchers_cleared_by_fkey FOREIGN KEY (cleared_by) REFERENCES public.users(id),
  CONSTRAINT check_vouchers_voided_by_fkey FOREIGN KEY (voided_by) REFERENCES public.users(id),
  CONSTRAINT check_vouchers_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.course_fees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  fee_code text NOT NULL,
  qualification_id uuid NOT NULL,
  fee_name text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  gl_account_id uuid NOT NULL,
  tax_category_id uuid,
  is_subject_to_ewt boolean NOT NULL DEFAULT false,
  ewt_rate numeric,
  category text CHECK (category = ANY (ARRAY['TUITION'::text, 'REGISTRATION'::text, 'CERTIFICATION'::text, 'ASSESSMENT'::text, 'MATERIALS'::text, 'MISCELLANEOUS'::text])),
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT course_fees_pkey PRIMARY KEY (id),
  CONSTRAINT course_fees_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT course_fees_qualification_id_fkey FOREIGN KEY (qualification_id) REFERENCES public.qualifications(id),
  CONSTRAINT course_fees_gl_account_id_fkey FOREIGN KEY (gl_account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT course_fees_tax_category_id_fkey FOREIGN KEY (tax_category_id) REFERENCES public.atc_categories(id)
);
CREATE TABLE public.employees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL CHECK (org_id IS NOT NULL),
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  designation character varying,
  tin character varying,
  sss character varying,
  philhealth character varying,
  pagibig character varying,
  basic_salary numeric NOT NULL DEFAULT 0 CHECK (basic_salary >= 0::numeric),
  bank_name character varying,
  bank_account character varying,
  is_active boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employees_pkey PRIMARY KEY (id),
  CONSTRAINT employees_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  enrollment_code character varying NOT NULL,
  student_id uuid NOT NULL,
  batch_id uuid NOT NULL,
  sponsor_id uuid,
  billing_status USER-DEFINED NOT NULL DEFAULT 'UNBILLED'::billing_status,
  enrollment_status USER-DEFINED NOT NULL DEFAULT 'ACTIVE'::enrollment_status,
  enrollment_date date NOT NULL DEFAULT CURRENT_DATE,
  total_fees numeric NOT NULL DEFAULT 0,
  billed_amount numeric NOT NULL DEFAULT 0,
  notes text,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  billing_type text NOT NULL DEFAULT 'BILLABLE'::text CHECK (billing_type = ANY (ARRAY['BILLABLE'::text, 'FREE_EXCESS'::text, 'FREE_SPONSORED'::text, 'MANUAL_FREE'::text])),
  CONSTRAINT enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT enrollments_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT enrollments_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.batches(id),
  CONSTRAINT enrollments_sponsor_id_fkey FOREIGN KEY (sponsor_id) REFERENCES public.sponsors(id)
);
CREATE TABLE public.exchange_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  from_currency character varying NOT NULL,
  to_currency character varying NOT NULL,
  rate numeric NOT NULL CHECK (rate > 0::numeric),
  effective_date date NOT NULL,
  source character varying NOT NULL DEFAULT 'MANUAL'::character varying,
  is_manual boolean DEFAULT true,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_by uuid,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  is_deleted boolean DEFAULT false,
  deleted_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT exchange_rates_pkey PRIMARY KEY (id),
  CONSTRAINT exchange_rates_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT exchange_rates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT exchange_rates_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT exchange_rates_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.feedback_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid,
  title text NOT NULL,
  description text NOT NULL,
  screenshot_data_url text,
  screenshot_name text,
  status text NOT NULL DEFAULT 'OPEN'::text CHECK (status = ANY (ARRAY['OPEN'::text, 'IN_PROGRESS'::text, 'RESOLVED'::text, 'CLOSED'::text])),
  priority text NOT NULL DEFAULT 'MEDIUM'::text CHECK (priority = ANY (ARRAY['LOW'::text, 'MEDIUM'::text, 'HIGH'::text, 'URGENT'::text])),
  created_by uuid,
  created_by_name text NOT NULL,
  created_by_role text NOT NULL,
  assigned_to uuid,
  admin_notes text,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT feedback_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_tickets_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT feedback_tickets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT feedback_tickets_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT feedback_tickets_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.fixed_assets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  category character varying,
  purchase_date date,
  purchase_cost numeric,
  accumulated_depreciation numeric DEFAULT 0,
  net_book_value numeric DEFAULT (purchase_cost - accumulated_depreciation),
  depreciation_method character varying DEFAULT 'STRAIGHT_LINE'::character varying,
  useful_life_years integer,
  gl_account_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fixed_assets_pkey PRIMARY KEY (id),
  CONSTRAINT fixed_assets_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT fixed_assets_gl_account_id_fkey FOREIGN KEY (gl_account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT fk_asset_gl_account FOREIGN KEY (gl_account_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.inventory_levels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  stock_item_id uuid NOT NULL,
  warehouse_location_id uuid NOT NULL,
  quantity_on_hand numeric DEFAULT 0,
  quantity_reserved numeric DEFAULT 0,
  quantity_available numeric DEFAULT 0,
  last_counted timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  CONSTRAINT inventory_levels_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_levels_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT inventory_levels_stock_item_id_fkey FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id),
  CONSTRAINT inventory_levels_warehouse_location_id_fkey FOREIGN KEY (warehouse_location_id) REFERENCES public.warehouse_locations(id)
);
CREATE TABLE public.inventory_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  reference_number character varying NOT NULL,
  stock_item_id uuid NOT NULL,
  transaction_type character varying NOT NULL CHECK (transaction_type::text = ANY (ARRAY['PURCHASE'::character varying, 'SALE'::character varying, 'ADJUSTMENT'::character varying, 'TRANSFER'::character varying, 'RETURN'::character varying, 'DAMAGE'::character varying, 'WRITEOFF'::character varying]::text[])),
  from_location_id uuid,
  to_location_id uuid NOT NULL,
  quantity numeric NOT NULL,
  unit_cost numeric NOT NULL,
  total_cost numeric NOT NULL,
  notes text,
  journal_entry_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_transactions_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT inventory_transactions_stock_item_id_fkey FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id),
  CONSTRAINT inventory_transactions_from_location_id_fkey FOREIGN KEY (from_location_id) REFERENCES public.warehouse_locations(id),
  CONSTRAINT inventory_transactions_to_location_id_fkey FOREIGN KEY (to_location_id) REFERENCES public.warehouse_locations(id),
  CONSTRAINT inventory_transactions_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
  CONSTRAINT inventory_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.invoice_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  line_number integer NOT NULL,
  description text NOT NULL,
  course_fee_id uuid,
  enrollment_id uuid,
  quantity numeric NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0,
  amount numeric NOT NULL DEFAULT 0,
  tax_category_id uuid,
  vat_amount numeric DEFAULT 0,
  gl_account_id uuid,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  net_amount numeric DEFAULT 0,
  gross_amount numeric DEFAULT 0,
  org_id uuid,
  classification_code text,
  assessment_registration_id uuid,
  line_type text NOT NULL DEFAULT 'MANUAL'::text CHECK (line_type = ANY (ARRAY['COURSE_FEE'::text, 'DISCOUNT'::text, 'ADJUSTMENT'::text, 'MANUAL'::text])),
  CONSTRAINT invoice_lines_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_lines_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT invoice_lines_course_fee_id_fkey FOREIGN KEY (course_fee_id) REFERENCES public.course_fees(id),
  CONSTRAINT invoice_lines_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  invoice_no character varying NOT NULL,
  sponsor_id uuid,
  student_id uuid,
  enrollment_id uuid,
  batch_id uuid,
  invoice_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'VOIDED'::invoice_status,
  subtotal numeric NOT NULL DEFAULT 0,
  vat_amount numeric NOT NULL DEFAULT 0,
  grand_total numeric NOT NULL DEFAULT 0,
  total_ewt_amount numeric NOT NULL DEFAULT 0,
  net_amount_due numeric NOT NULL DEFAULT 0,
  amount_paid numeric NOT NULL DEFAULT 0,
  balance_due numeric NOT NULL DEFAULT 0,
  ewt_rate numeric,
  is_subject_to_ewt boolean NOT NULL DEFAULT false,
  reference character varying,
  terms character varying,
  notes text,
  journal_entry_id uuid,
  posted_by uuid,
  posted_at timestamp with time zone,
  voided_by uuid,
  voided_at timestamp with time zone,
  void_reason text,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  vat_pricing text DEFAULT 'INCLUSIVE'::text,
  vat_rate numeric DEFAULT 0.12,
  gl_entry_number text,
  assessment_registration_id uuid,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT invoices_sponsor_id_fkey FOREIGN KEY (sponsor_id) REFERENCES public.sponsors(id),
  CONSTRAINT invoices_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT invoices_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id),
  CONSTRAINT invoices_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.batches(id)
);
CREATE TABLE public.item_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  total_amount numeric NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT item_groups_pkey PRIMARY KEY (id),
  CONSTRAINT item_groups_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT item_groups_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  unit_price numeric,
  income_account_id uuid,
  expense_account_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  tax_category_id uuid,
  CONSTRAINT items_pkey PRIMARY KEY (id),
  CONSTRAINT items_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_item_income_account FOREIGN KEY (income_account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT fk_item_expense_account FOREIGN KEY (expense_account_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.journal_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  period_id character varying NOT NULL DEFAULT 'CURRENT'::character varying,
  date date NOT NULL,
  description character varying NOT NULL,
  reference character varying,
  status character varying DEFAULT 'POSTED'::character varying CHECK (status::text = ANY (ARRAY['DRAFT'::character varying, 'POSTED'::character varying, 'REVERSED'::character varying, 'REVISION_REQUESTED'::character varying]::text[])),
  created_by uuid,
  source_type character varying DEFAULT 'MANUAL'::character varying CHECK (source_type::text = ANY (ARRAY['MANUAL'::character varying, 'INVOICE'::character varying, 'BILL'::character varying, 'PAYMENT'::character varying, 'COLLECTION'::character varying, 'DEPRECIATION'::character varying, 'TRANSFER'::character varying, 'PURCHASE_ORDER'::character varying, 'PAYROLL'::character varying, 'CREDIT_MEMO'::character varying, 'GR_IR'::character varying, 'ACCRUAL'::character varying, 'REVERSAL'::character varying, 'APPLICATION'::character varying, 'VOID'::character varying, 'DEPOSIT'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  approved_by uuid,
  approved_at timestamp with time zone,
  gl_entry_number character varying,
  review_comments jsonb DEFAULT '[]'::jsonb,
  updated_by text,
  source_ref uuid,
  deposit_id uuid,
  reversed_by text,
  reversed_at timestamp with time zone,
  reversal_reason text,
  original_entry_id uuid,
  CONSTRAINT journal_entries_pkey PRIMARY KEY (id),
  CONSTRAINT journal_entries_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT journal_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT journal_entries_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT journal_entries_deposit_id_fkey FOREIGN KEY (deposit_id) REFERENCES public.bank_deposits(id)
);
CREATE TABLE public.journal_entry_lines (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entry_id uuid NOT NULL,
  account_id uuid NOT NULL,
  debit numeric NOT NULL DEFAULT 0,
  credit numeric NOT NULL DEFAULT 0,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT journal_entry_lines_pkey PRIMARY KEY (id),
  CONSTRAINT journal_entry_lines_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES public.journal_entries(id),
  CONSTRAINT journal_entry_lines_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.journal_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  journal_entry_id uuid NOT NULL,
  account_id uuid NOT NULL,
  debit numeric DEFAULT 0,
  credit numeric DEFAULT 0,
  memo text,
  contact_id uuid,
  contact_type text CHECK (contact_type = ANY (ARRAY['STUDENT'::text, 'TRAINER'::text, 'SPONSOR'::text, 'VENDOR'::text, 'OTHER'::text, 'EMPLOYEE'::text])),
  batch_id uuid,
  item_id uuid,
  asset_id uuid,
  is_cleared boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  description text,
  classification_code text,
  tax_category_id uuid,
  CONSTRAINT journal_lines_pkey PRIMARY KEY (id),
  CONSTRAINT journal_lines_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
  CONSTRAINT journal_lines_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.locations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  name character varying NOT NULL,
  address text,
  capacity integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT locations_pkey PRIMARY KEY (id),
  CONSTRAINT locations_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  currency character varying DEFAULT 'PHP'::character varying,
  tax_id character varying,
  is_vat_registered boolean DEFAULT false,
  subscription_status character varying DEFAULT 'TRIAL'::character varying CHECK (subscription_status::text = ANY (ARRAY['ACTIVE'::character varying, 'TRIAL'::character varying, 'SUSPENDED'::character varying, 'EXPIRED'::character varying, 'PENDING'::character varying]::text[])),
  plan_type character varying DEFAULT 'BASIC'::character varying CHECK (plan_type::text = ANY (ARRAY['BASIC'::character varying, 'PROFESSIONAL'::character varying, 'ENTERPRISE'::character varying]::text[])),
  pending_plan_type character varying,
  payment_reference character varying,
  license_expiry date,
  primary_color character varying DEFAULT '#4f46e5'::character varying,
  logo_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payables (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  payable_number text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['utilities'::text, 'supplies'::text, 'training_materials'::text, 'contractor_services'::text, 'assessments'::text, 'insurance'::text, 'government_obligations'::text, 'scholarship_advances'::text, 'employee_reimbursements'::text, 'other'::text])),
  description text NOT NULL,
  amount numeric NOT NULL,
  bill_date date NOT NULL,
  due_date date NOT NULL,
  payment_date date,
  currency text DEFAULT 'PHP'::text,
  status text DEFAULT 'for_approval'::text CHECK (status = ANY (ARRAY['for_approval'::text, 'approved'::text, 'paid'::text, 'partially_paid'::text, 'cancelled'::text])),
  reference_document text,
  journal_entry_id uuid,
  gl_account_id uuid,
  notes text,
  withholding_type text CHECK (withholding_type = ANY (ARRAY['EXPANDED'::text, 'FINAL'::text])),
  atc_item_id uuid,
  atc_rate_id uuid,
  applied_rate_percent numeric DEFAULT 0,
  withholding_amount numeric DEFAULT 0,
  net_payable numeric,
  created_by uuid NOT NULL,
  approved_by uuid,
  paid_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  approved_at timestamp with time zone,
  paid_at timestamp with time zone,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT payables_pkey PRIMARY KEY (id),
  CONSTRAINT payables_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT payables_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT payables_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
  CONSTRAINT payables_gl_account_id_fkey FOREIGN KEY (gl_account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT payables_atc_item_id_fkey FOREIGN KEY (atc_item_id) REFERENCES public.atc_items(id),
  CONSTRAINT payables_atc_rate_id_fkey FOREIGN KEY (atc_rate_id) REFERENCES public.atc_rates(id),
  CONSTRAINT payables_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT payables_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT payables_paid_by_fkey FOREIGN KEY (paid_by) REFERENCES public.users(id)
);
CREATE TABLE public.payment_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_id uuid NOT NULL,
  invoice_id uuid NOT NULL,
  amount_applied numeric NOT NULL CHECK (amount_applied > 0::numeric),
  is_reversed boolean DEFAULT false,
  reversal_reason text,
  reversed_at timestamp with time zone,
  reversed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_applications_pkey PRIMARY KEY (id),
  CONSTRAINT payment_applications_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT payment_applications_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT payment_applications_reversed_by_fkey FOREIGN KEY (reversed_by) REFERENCES public.users(id),
  CONSTRAINT payment_applications_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.payment_histories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL CHECK (org_id IS NOT NULL),
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency character varying NOT NULL DEFAULT 'USD'::character varying,
  due_date date NOT NULL,
  paid_date date,
  status character varying NOT NULL DEFAULT 'PENDING'::character varying CHECK (status::text = ANY (ARRAY['PAID'::character varying, 'PENDING'::character varying, 'OVERDUE'::character varying, 'CANCELLED'::character varying]::text[])),
  plan_type character varying,
  description text,
  invoice_number character varying,
  payment_method character varying,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_histories_pkey PRIMARY KEY (id),
  CONSTRAINT payment_histories_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  payment_no character varying NOT NULL,
  sponsor_id uuid,
  student_id uuid,
  payment_date date NOT NULL DEFAULT CURRENT_DATE,
  status character varying NOT NULL DEFAULT 'DRAFT'::character varying CHECK (status::text = ANY (ARRAY['DRAFT'::character varying, 'POSTED'::character varying, 'VOIDED'::character varying]::text[])),
  payment_method character varying NOT NULL DEFAULT 'CHECK'::character varying CHECK (payment_method::text = ANY (ARRAY['CASH'::character varying, 'CHECK'::character varying, 'BANK_TRANSFER'::character varying, 'CREDIT_CARD'::character varying, 'EWALLET'::character varying, 'OFFSET'::character varying]::text[])),
  ref_no character varying,
  bank_account_id uuid,
  check_number character varying,
  check_date date,
  amount_received numeric NOT NULL DEFAULT 0,
  ewt_amount_certified numeric NOT NULL DEFAULT 0,
  total_applied numeric NOT NULL DEFAULT 0,
  customer_deposit_balance numeric NOT NULL DEFAULT 0,
  journal_entry_id uuid,
  voided_at timestamp with time zone,
  voided_by uuid,
  void_reason text,
  posted_at timestamp with time zone,
  posted_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT payments_sponsor_id_fkey FOREIGN KEY (sponsor_id) REFERENCES public.sponsors(id),
  CONSTRAINT payments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT payments_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
  CONSTRAINT payments_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
  CONSTRAINT payments_voided_by_fkey FOREIGN KEY (voided_by) REFERENCES public.users(id),
  CONSTRAINT payments_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES public.users(id),
  CONSTRAINT payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT payments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT payments_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.payroll_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL CHECK (org_id IS NOT NULL),
  payroll_run_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  gross_pay numeric NOT NULL DEFAULT 0,
  deductions_tax numeric NOT NULL DEFAULT 0,
  deductions_sss numeric NOT NULL DEFAULT 0,
  deductions_philhealth numeric NOT NULL DEFAULT 0,
  deductions_pagibig numeric NOT NULL DEFAULT 0,
  deductions_other numeric NOT NULL DEFAULT 0,
  net_pay numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payroll_lines_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_lines_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT payroll_lines_payroll_run_id_fkey FOREIGN KEY (payroll_run_id) REFERENCES public.payroll_runs(id),
  CONSTRAINT payroll_lines_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.payroll_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL CHECK (org_id IS NOT NULL),
  period_start date NOT NULL,
  period_end date NOT NULL,
  status character varying NOT NULL DEFAULT 'DRAFT'::character varying CHECK (status::text = ANY (ARRAY['DRAFT'::character varying, 'POSTED'::character varying]::text[])),
  total_gross numeric NOT NULL DEFAULT 0,
  total_deductions numeric NOT NULL DEFAULT 0,
  total_net numeric NOT NULL DEFAULT 0,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payroll_runs_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_runs_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.purchase_order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  po_id uuid NOT NULL,
  item_id uuid NOT NULL,
  quantity numeric NOT NULL,
  unit_price numeric NOT NULL,
  total_amount numeric DEFAULT (quantity * unit_price),
  received_quantity numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT purchase_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_items_po_id_fkey FOREIGN KEY (po_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT purchase_order_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(id)
);
CREATE TABLE public.purchase_orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  po_number character varying NOT NULL,
  order_date date NOT NULL,
  expected_delivery_date date,
  status character varying DEFAULT 'DRAFT'::character varying CHECK (status::text = ANY (ARRAY['DRAFT'::character varying, 'SENT'::character varying, 'APPROVED'::character varying, 'RECEIVED'::character varying, 'CANCELLED'::character varying]::text[])),
  total_amount numeric NOT NULL DEFAULT 0,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  gl_entry_number character varying,
  approved_by uuid,
  approved_at timestamp with time zone,
  CONSTRAINT purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_orders_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT purchase_orders_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT purchase_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.qualifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  duration_days integer NOT NULL,
  sector character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT qualifications_pkey PRIMARY KEY (id),
  CONSTRAINT qualifications_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.recurring_journal_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  frequency character varying NOT NULL CHECK (frequency::text = ANY (ARRAY['DAILY'::character varying, 'WEEKLY'::character varying, 'BIWEEKLY'::character varying, 'MONTHLY'::character varying, 'QUARTERLY'::character varying, 'SEMIANNUAL'::character varying, 'ANNUAL'::character varying, 'CUSTOM'::character varying]::text[])),
  start_date date NOT NULL,
  end_date date,
  next_run_date date NOT NULL,
  last_run_date date,
  max_runs integer,
  times_run integer DEFAULT 0,
  status character varying NOT NULL DEFAULT 'ACTIVE'::character varying CHECK (status::text = ANY (ARRAY['ACTIVE'::character varying, 'PAUSED'::character varying, 'COMPLETED'::character varying, 'INACTIVE'::character varying]::text[])),
  auto_post boolean DEFAULT true,
  last_generated_entry_id uuid,
  template_entry jsonb NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_by uuid,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  is_deleted boolean DEFAULT false,
  deleted_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT recurring_journal_entries_pkey PRIMARY KEY (id),
  CONSTRAINT recurring_journal_entries_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT recurring_journal_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT recurring_journal_entries_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT recurring_journal_entries_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.reorder_points (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  stock_item_id uuid NOT NULL,
  min_level numeric NOT NULL,
  max_level numeric NOT NULL,
  reorder_quantity numeric NOT NULL,
  lead_time_days integer DEFAULT 7,
  last_reorder_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT reorder_points_pkey PRIMARY KEY (id),
  CONSTRAINT reorder_points_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT reorder_points_stock_item_id_fkey FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id)
);
CREATE TABLE public.schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL CHECK (org_id IS NOT NULL),
  trainer_id uuid NOT NULL CHECK (trainer_id IS NOT NULL),
  location_id uuid,
  slots jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT schedules_pkey PRIMARY KEY (id),
  CONSTRAINT schedules_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT schedules_trainer_id_fkey FOREIGN KEY (trainer_id) REFERENCES public.trainers(id)
);
CREATE TABLE public.sponsors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  name character varying NOT NULL,
  contact_person character varying,
  email character varying,
  phone character varying,
  address text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  ar_account_id uuid,
  sponsor_code text,
  tin text,
  tax_type text CHECK (tax_type = ANY (ARRAY['VAT'::text, 'NON_VAT'::text, 'ZERO_RATED'::text])),
  ewt_rate numeric,
  CONSTRAINT sponsors_pkey PRIMARY KEY (id),
  CONSTRAINT sponsors_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT sponsors_ar_account_id_fkey FOREIGN KEY (ar_account_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.stock_adjustments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  adjustment_number character varying NOT NULL,
  stock_item_id uuid NOT NULL,
  warehouse_location_id uuid NOT NULL,
  quantity_change numeric NOT NULL,
  reason character varying NOT NULL,
  notes text,
  approved_by uuid,
  approval_date timestamp with time zone,
  journal_entry_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT stock_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT stock_adjustments_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT stock_adjustments_stock_item_id_fkey FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id),
  CONSTRAINT stock_adjustments_warehouse_location_id_fkey FOREIGN KEY (warehouse_location_id) REFERENCES public.warehouse_locations(id),
  CONSTRAINT stock_adjustments_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT stock_adjustments_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
  CONSTRAINT stock_adjustments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.stock_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  unit_price numeric DEFAULT 0,
  cost_price numeric DEFAULT 0,
  warehouse_location_id uuid NOT NULL,
  income_account_id uuid,
  cogs_account_id uuid,
  expense_account_id uuid,
  tax_category_id uuid,
  valuation_method character varying DEFAULT 'FIFO'::character varying CHECK (valuation_method::text = ANY (ARRAY['FIFO'::character varying, 'LIFO'::character varying, 'WEIGHTED_AVERAGE'::character varying, 'STANDARD_COST'::character varying]::text[])),
  min_stock_level numeric DEFAULT 0,
  max_stock_level numeric DEFAULT 0,
  reorder_quantity numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT stock_items_pkey PRIMARY KEY (id),
  CONSTRAINT stock_items_warehouse_location_id_fkey FOREIGN KEY (warehouse_location_id) REFERENCES public.warehouse_locations(id),
  CONSTRAINT stock_items_income_account_id_fkey FOREIGN KEY (income_account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT stock_items_cogs_account_id_fkey FOREIGN KEY (cogs_account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT stock_items_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT stock_items_expense_account_id_fkey FOREIGN KEY (expense_account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT stock_items_tax_category_id_fkey FOREIGN KEY (tax_category_id) REFERENCES public.atc_categories(id)
);
CREATE TABLE public.students (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  uli character varying NOT NULL UNIQUE,
  last_name character varying NOT NULL,
  first_name character varying NOT NULL,
  middle_name character varying,
  extension character varying,
  sex character varying,
  date_of_birth date NOT NULL,
  birth_region character varying,
  birth_province character varying,
  birth_city character varying,
  civil_status character varying,
  educational_attainment character varying,
  nationality character varying,
  email character varying NOT NULL,
  contact_number character varying,
  street character varying,
  barangay character varying,
  city character varying,
  district character varying,
  province character varying,
  guardian character varying,
  location_id uuid,
  sponsor_id uuid,
  documents ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  profile_photo text,
  mailing_region text,
  tesda_employment_status text,
  tesda_employment_type text,
  tesda_learner_classifications ARRAY,
  tesda_other_classification text,
  tesda_disability_types ARRAY,
  tesda_disability_causes ARRAY,
  tesda_course_qualification text,
  tesda_scholarship_package text,
  tesda_privacy_consent text,
  CONSTRAINT students_pkey PRIMARY KEY (id),
  CONSTRAINT students_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT students_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT students_sponsor_id_fkey FOREIGN KEY (sponsor_id) REFERENCES public.sponsors(id)
);
CREATE TABLE public.tax_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  code character varying NOT NULL,
  description text,
  type character varying NOT NULL DEFAULT 'VAT'::character varying,
  rate numeric NOT NULL DEFAULT 0.1200,
  is_inclusive boolean NOT NULL DEFAULT true,
  output_account_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tax_type text NOT NULL,
  CONSTRAINT tax_categories_pkey PRIMARY KEY (id),
  CONSTRAINT tax_categories_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT tax_categories_output_account_id_fkey FOREIGN KEY (output_account_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.trainer_schedules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  trainer_id uuid NOT NULL,
  location_id uuid,
  schedule_date date DEFAULT CURRENT_DATE,
  start_time time without time zone,
  end_time time without time zone,
  subject character varying,
  batch_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  slots jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT trainer_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT trainer_schedules_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.batches(id),
  CONSTRAINT trainer_schedules_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT trainer_schedules_trainer_id_fkey FOREIGN KEY (trainer_id) REFERENCES public.trainers(id),
  CONSTRAINT trainer_schedules_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.trainers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  middle_name character varying,
  email character varying NOT NULL,
  contact_number character varying,
  specialization text,
  qualification_ids ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trainers_pkey PRIMARY KEY (id),
  CONSTRAINT trainers_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  salt character varying NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['SYSTEM_ADMIN'::text, 'ADMIN'::text, 'PRESIDENT'::text, 'FINANCE_MANAGER'::text, 'ACCOUNTANT'::text, 'AR_SPECIALIST'::text, 'AP_SPECIALIST'::text, 'AP_CLERK'::text, 'AP_SUPERVISOR'::text, 'TREASURY'::text, 'AUDITOR'::text, 'REGISTRAR'::text, 'TRAINER'::text, 'STUDENT'::text, 'VIEWER'::text])),
  last_login_at timestamp with time zone,
  is_active boolean DEFAULT true,
  failed_login_attempts integer DEFAULT 0,
  locked_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  auth_uid uuid,
  trainer_id uuid,
  student_id uuid,
  last_name text,
  profile_photo text,
  contact_number text,
  address text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.vendor_tax_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  atc_item_id uuid,
  atc_rate_id uuid,
  withholding_type text CHECK (withholding_type = ANY (ARRAY['EXPANDED'::text, 'FINAL'::text])),
  is_active boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT vendor_tax_settings_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_tax_settings_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT vendor_tax_settings_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT vendor_tax_settings_atc_item_id_fkey FOREIGN KEY (atc_item_id) REFERENCES public.atc_items(id),
  CONSTRAINT vendor_tax_settings_atc_rate_id_fkey FOREIGN KEY (atc_rate_id) REFERENCES public.atc_rates(id)
);
CREATE TABLE public.vendors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  org_id uuid NOT NULL,
  name character varying NOT NULL,
  category character varying,
  email character varying,
  contact_number character varying,
  address text,
  ap_account_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vendors_pkey PRIMARY KEY (id),
  CONSTRAINT vendors_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_vendor_ap_account FOREIGN KEY (ap_account_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.warehouse_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  address text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT warehouse_locations_pkey PRIMARY KEY (id),
  CONSTRAINT warehouse_locations_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);