import React, { useMemo, useState } from 'react';
import { BookOpen, Search, ScrollText } from 'lucide-react';
import { AccountClass, ChartOfAccount, JournalEntry, JournalLine, Vendor } from '../types';

interface BaseProps {
  entries: JournalEntry[];
  lines: JournalLine[];
  vendors: Vendor[];
  accounts: ChartOfAccount[];
  currency?: string;
}

const AP_SOURCE_TYPES = new Set(['BILL', 'PAYMENT', 'CREDIT_MEMO', 'DEBIT_MEMO', 'REVERSAL', 'GR_IR', 'PURCHASE_ORDER']);
const money = (value: number, currency = 'PHP') => new Intl.NumberFormat('en-PH', { style: 'currency', currency }).format(value || 0);
const entryReference = (entry: JournalEntry) => entry.glEntryNumber || entry.reference || entry.id;

export const APJournalVouchersView: React.FC<BaseProps> = ({ entries, lines, vendors, currency = 'PHP' }) => {
  const [search, setSearch] = useState('');
  const rows = useMemo(() => entries
    .filter(entry => (entry.status === 'POSTED' || entry.status === 'REVERSED') && (
      AP_SOURCE_TYPES.has(String(entry.sourceType).toUpperCase()) ||
      lines.some(line => line.journalEntryId === entry.id && line.contactType === 'VENDOR')
    ))
    .map(entry => {
      const entryLines = lines.filter(line => line.journalEntryId === entry.id);
      const vendorId = entryLines.find(line => line.contactType === 'VENDOR')?.contactId;
      return {
        entry,
        vendor: vendors.find(vendor => vendor.id === vendorId)?.name || 'Multiple / Unassigned',
        debit: entryLines.reduce((sum, line) => sum + Number(line.debit || 0), 0),
        credit: entryLines.reduce((sum, line) => sum + Number(line.credit || 0), 0)
      };
    })
    .filter(row => [entryReference(row.entry), row.entry.description, row.entry.sourceType, row.vendor]
      .join(' ').toLowerCase().includes(search.trim().toLowerCase()))
    .sort((a, b) => (b.entry.date || '').localeCompare(a.entry.date || '')),
  [entries, lines, vendors, search]);

  return (
    <div className="space-y-5">
      <div>
        <h2 className="flex items-center gap-2 text-xl font-semibold text-gray-800"><ScrollText className="text-brand" size={21} /> AP Journal Vouchers</h2>
        <p className="text-sm italic text-gray-500">Posted journal activity generated by AP bills, vendor payments, purchases, and reversals.</p>
      </div>
      <div className="relative max-w-xl">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
        <input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search reference, vendor, source, or description..." className="w-full rounded border border-gray-200 bg-white py-2.5 pl-9 pr-3 text-sm outline-none focus:border-brand" />
      </div>
      <div className="overflow-hidden rounded border border-gray-200 bg-white shadow-sm">
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200 text-sm">
            <thead className="bg-brand text-white"><tr>
              <th className="px-4 py-3 text-left">Date</th><th className="px-4 py-3 text-left">GL Reference</th><th className="px-4 py-3 text-left">Source</th><th className="px-4 py-3 text-left">Vendor</th><th className="px-4 py-3 text-left">Description</th><th className="px-4 py-3 text-right">Debit</th><th className="px-4 py-3 text-right">Credit</th>
            </tr></thead>
            <tbody className="divide-y divide-gray-100">
              {rows.length ? rows.map(({ entry, vendor, debit, credit }) => <tr key={entry.id} className="hover:bg-gray-50">
                <td className="px-4 py-3 text-gray-600">{entry.date}</td><td className="px-4 py-3 font-mono font-semibold text-brand">{entryReference(entry)}</td><td className="px-4 py-3"><span className="rounded bg-gray-100 px-2 py-1 text-xs font-semibold text-gray-600">{entry.sourceType}</span></td><td className="px-4 py-3 font-medium text-gray-700">{vendor}</td><td className="max-w-sm truncate px-4 py-3 text-gray-600">{entry.description}</td><td className="px-4 py-3 text-right font-mono">{money(debit, currency)}</td><td className="px-4 py-3 text-right font-mono">{money(credit, currency)}</td>
              </tr>) : <tr><td colSpan={7} className="px-4 py-12 text-center text-gray-400">No AP journal transactions found.</td></tr>}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export const VendorLedgerView: React.FC<BaseProps> = ({ entries, lines, vendors, accounts, currency = 'PHP' }) => {
  const [vendorId, setVendorId] = useState('');
  const rows = useMemo(() => {
    let balance = 0;
    return entries
      .filter(entry => entry.status === 'POSTED' || entry.status === 'REVERSED')
      .sort((a, b) => (a.date || '').localeCompare(b.date || ''))
      .flatMap(entry => {
        const apLines = lines.filter(line => line.journalEntryId === entry.id && line.contactType === 'VENDOR' && line.contactId === vendorId)
          .filter(line => accounts.find(account => account.id === line.accountId)?.class === AccountClass.LIABILITY);
        if (!apLines.length) return [];
        const debit = apLines.reduce((sum, line) => sum + Number(line.debit || 0), 0);
        const credit = apLines.reduce((sum, line) => sum + Number(line.credit || 0), 0);
        balance += credit - debit;
        return [{ entry, debit, credit, balance }];
      });
  }, [entries, lines, accounts, vendorId]);

  return (
    <div className="space-y-5">
      <div>
        <h2 className="flex items-center gap-2 text-xl font-semibold text-gray-800"><BookOpen className="text-brand" size={21} /> Vendor Ledger</h2>
        <p className="text-sm italic text-gray-500">Vendor-level AP movements and running liability balance.</p>
      </div>
      <select value={vendorId} onChange={event => setVendorId(event.target.value)} className="w-full max-w-xl rounded border border-gray-200 bg-white px-4 py-2.5 text-sm font-medium outline-none focus:border-brand">
        <option value="">Select vendor...</option>
        {[...vendors].sort((a, b) => a.name.localeCompare(b.name)).map(vendor => <option key={vendor.id} value={vendor.id}>{vendor.name}</option>)}
      </select>
      <div className="overflow-hidden rounded border border-gray-200 bg-white shadow-sm">
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200 text-sm">
            <thead className="bg-brand text-white"><tr><th className="px-4 py-3 text-left">Date</th><th className="px-4 py-3 text-left">Reference</th><th className="px-4 py-3 text-left">Description</th><th className="px-4 py-3 text-right">Debit</th><th className="px-4 py-3 text-right">Credit</th><th className="px-4 py-3 text-right">Balance</th></tr></thead>
            <tbody className="divide-y divide-gray-100">
              {!vendorId ? <tr><td colSpan={6} className="px-4 py-12 text-center text-gray-400">Select a vendor to view its ledger.</td></tr> : rows.length ? rows.map(({ entry, debit, credit, balance }) => <tr key={entry.id} className="hover:bg-gray-50"><td className="px-4 py-3 text-gray-600">{entry.date}</td><td className="px-4 py-3 font-mono font-semibold text-brand">{entryReference(entry)}</td><td className="px-4 py-3 text-gray-600">{entry.description}</td><td className="px-4 py-3 text-right font-mono">{money(debit, currency)}</td><td className="px-4 py-3 text-right font-mono">{money(credit, currency)}</td><td className="px-4 py-3 text-right font-mono font-semibold text-gray-800">{money(balance, currency)}</td></tr>) : <tr><td colSpan={6} className="px-4 py-12 text-center text-gray-400">No posted vendor ledger activity found.</td></tr>}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
